// Carefully curated from the awesome list https://github.com/sindresorhus/awesome/blob/master/readme.md
export var Technologies = {
  'Platforms': [
    'Node.js',
    'Frontend Development',
    'iOS',
    'Android',
    'IoT & Hybrid Apps',
    'Electron',
    'Cordova',
    'React Native',
    'Xamarin',
    'Linux',
    'Containers',
    'OS X',
    'Command-Line',
    'Screensavers',
    'watchOS',
    'JVM',
    'Salesforce',
    'Amazon Web Services',
    'Windows',
    'IPFS',
    'Fuse',
    'Heroku',
  ],
  'Programming Languages': [
    'JavaScript',
    'Swift',
    'Python',
    'Rust',
    'Haskell',
    'PureScript',
    'Go',
    'Scala',
    'Ruby',
    'Clojure',
    'ClojureScript',
    'Elixir',
    'Elm',
    'Erlang',
    'Julia',
    'Lua',
    'C',
    'R',
    'D',
    'Common Lisp',
    'Perl',
    'Groovy',
    'Dart',
    'Java',
    'Kotlin',
    'OCaml',
    'Coldfusion',
    'Fortran',
    '.NET',
    'PHP',
    'Delphi',
    'Assembler',
    'AutoHotkey',
    'AutoIt',
    'Crystal',
    'TypeScript',
  ],
  'Frontend Development': [
    'ES6 Tools',
    'Web Performance Optimization',
    'Web Tools',
    'CSS',
    'React',
    'Web Components',
    'Polymer',
    'Angular 2',
    'Angular',
    'Backbone',
    'HTML5',
    'SVG',
    'Canvas',
    'KnockoutJS',
    'Dojo Toolkit',
    'Inspiration',
    'Ember',
    'Android UI',
    'iOS UI',
    'Meteor',
    'BEM',
    'Flexbox',
    'Web Typography',
    'Web Accessibility',
    'Material Design',
    'D3',
    'Emails',
    'jQuery',
    'Web Audio',
    'Offline-First',
    'Static Website Services',
    'A-Frame VR',
    'Cycle.js',
    'Text Editing',
    'Motion UI Design',
    'Vue.js',
    'Marionette.js',
    'Aurelia',
    'Charting',
    'Ionic Framework 2',
    'Chrome DevTools',
    'PostCSS'
  ],
  'Backend Development': [
    'Django',
    'Flask',
    'Docker',
    'Vagrant',
    'Pyramid',
    'Play1 Framework',
    'CakePHP',
    'Symfony',
    'Laravel',
    'Rails',
    'Phalcon',
    'nginx',
    'Dropwizard',
    'Kubernetes',
    'Lumen'
  ],
  'Computer Science': [
    'University Courses',
    'Data Science',
    'Machine Learning',
    'Speech and Natural Language Processing',
    'Linguistics',
    'Cryptography',
    'Computer Vision',
    'Deep Learning',
    'Deep Vision',
    'Open Source Society University',
    'Functional Programming',
    'Static Analysis & Code Quality',
    'Software-Defined Networking'
  ],
  'Big Data': [
    'Big Data',
    'Public Datasets',
    'Hadoop',
    'Data Engineering',
    'Streaming'
  ],
  'Editors': [
    'Sublime Text',
    'Vim',
    'Emacs',
    'Atom',
    'Visual Studio Code'
  ],
  'Gaming': [
    'Game Development',
    'Game Talks',
    'Godot',
    'Open Source Games',
    'Unity',
    'Chess',
    'LÖVE',
    'PICO-8'
  ],
  'Databases': [
    'Database',
    'MySQL',
    'SQLAlchemy',
    'InfluxDB',
    'Neo4j',
    'Doctrine',
    'MongoDB',
    'RethinkDB'
  ],
  'Miscellaneous': [
    'JSON',
    'Discounts for Student Developers',
    'Slack',
    'Conferences',
    'GeoJSON',
    'Sysadmin',
    'Radio',
    'Awesome',
    'Analytics',
    'Open Companies',
    'REST',
    'Selenium',
    'Endangered Languages',
    'Continuous Delivery',
    'Services Engineering',
    'Free for Developers',
    'Bitcoin',
    'Answers',
    'Sketch',
    'Places to Post Your Startup',
    'PCAPTools',
    'Remote Jobs',
    'Boilerplate Projects',
    'Readme',
    'Tools',
    'Styleguides',
    'Design and Development Guides',
    'Software Engineering Blogs',
    'Self Hosted',
    'FOSS Production Apps',
    'Gulp',
    'AMA',
    'Open Source Photography',
    'OpenGL',
    'Productivity',
    'GraphQL',
    'Transit',
    'Research Tools',
    'Niche Job Boards',
    'Data Visualization',
    'Social Media Share Links',
    'JSON Datasets',
    'Microservices',
    'Unicode Code Points',
    'Internet of Things',
    'Beginner-Friendly Projects',
    'Bluetooth Beacons',
    'Programming Interviews',
    'Ripple',
    'Katas',
    'Tools for Activism',
    'TAP',
    'Robotics',
    'MQTT',
    'Hacking Spots',
    'For Girls',
    'Vorpal',
    'OKR Methodology',
    'Vulkan',
    'LaTeX',
    'Network Analysis',
    'Economics',
    'Electric Guitar Specifications',
    'Funny Markov Chains'
  ]
};
